[workspace]
resolver = "2"
members = [
    "packages/*",
]

[workspace.dependencies]
dioxus = { version = "0.7.1" }
dioxus-sdk = { version = "0.7", features = ["storage"] }

opensubsonic-cli = { path = "packages/opensubsonic-cli" }
cadence-player = { path = "packages/cadence-player" }

tracing = "0.1"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1.0", default-features = false  }
async-trait = "0.1"
once_cell = "1.21.3"
thiserror = "1.0"
url = "2.5.7"

# web
howler-wasm = { path = "packages/howler-wasm" }
web-sys = { version = "0.3.82", features = ["Window", "AudioContext", "AudioContextState"] }
wasm-bindgen-futures = "0.4.55"
