[package]
name = "shazam-fingerprint"
version = "0.1.0"
edition = "2024"
description = "Shazam-compatible audio fingerprinting library"

[dependencies]
chfft = "0.3.4"
byteorder = "1.3.4"
crc32fast = "1.2.0"
base64 = { workspace = true }

