[application]
name = "Cadence"
out_dir = "dist"
asset_dir = "public"
android_min_sdk_version = 35
android_main_activity = "../../android/sources/MainActivity.kt"
android_manifest = "../../AndroidManifest.xml"

[web.app]
title = "Cadence"

[web.watcher]
reload_html = true
watch_path = ["src", "public"]

[bundle]
identifier = "org.hoohoot"
publisher = "Cadence"
icon = ["assets/icon.png"]
