[package]
name = "cadence-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { workspace = true, features = ["router"] }
dioxus-sdk = { workspace = true }
dioxus-primitives.workspace = true
cadence-core = { workspace = true }
