[package]
name = "ui"
version = "0.1.0"
edition = "2024"

[dependencies]
cadence-player.workspace = true
tokio.workspace = true
dioxus = { workspace = true }
serde = { workspace = true }
opensubsonic-cli.workspace = true
reqwest = { workspace = true }

# [target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys.workspace = true
wasm-bindgen-futures.workspace = true
