[package]
name = "cadence-core"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus.workspace = true
tokio = { workspace = true, features = ["sync"] }
opensubsonic-cli = { workspace = true }
cadence-player = { workspace = true }
serde = { workspace = true }
